package primer_final;

/**
 *
 * @author alanalcaraz
 */
import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class BaseInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form BaseInterfaz
     */
    public BaseInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        InterfazPrincipal = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fecha = new javax.swing.JLabel();
        bienvenido = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botonesMenu = new javax.swing.JLayeredPane();
        boton_pagarTarjeta = new java.awt.Button();
        boton_deposito = new java.awt.Button();
        boton_pagarServicio = new java.awt.Button();
        boton_consultarSaldo = new java.awt.Button();
        boton_acercaSistema = new java.awt.Button();
        boton_transferenciaCuenta = new java.awt.Button();
        boton_salir1 = new java.awt.Button();
        separador = new javax.swing.JLayeredPane();
        label1 = new java.awt.Label();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        panel1 = new java.awt.Panel();
        boton_cancelarTransaccion = new java.awt.Button();
        boton_confirmarTransaccion = new java.awt.Button();
        cuentaDestino = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        cuentaDestino1 = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        cuentaDestino2 = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        cuentaDestino3 = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        cuentaDestino4 = new javax.swing.JTextField();
        cuentaDestino5 = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1020, 660));
        setMinimumSize(new java.awt.Dimension(1020, 660));
        setPreferredSize(new java.awt.Dimension(1020, 660));
        setResizable(false);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1020, 660));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1020, 660));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1020, 660));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InterfazPrincipal.setEnabled(false);
        InterfazPrincipal.setMaximumSize(new java.awt.Dimension(1020, 640));
        InterfazPrincipal.setMinimumSize(new java.awt.Dimension(1020, 640));
        InterfazPrincipal.setPreferredSize(new java.awt.Dimension(1020, 640));

        jLayeredPane1.setEnabled(false);
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1020, 640));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1020, 640));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1020, 640));

        fecha.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Fecha: dd/mm/aaaa");

        bienvenido.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        bienvenido.setText("Bienvenido, usuario!");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/primer_final/Logo 350x350.png"))); // NOI18N

        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 500));

        boton_pagarTarjeta.setActionCommand("pagarTarjeta");
        boton_pagarTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_pagarTarjeta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_pagarTarjeta.setLabel("Pagar Tarjeta");
        boton_pagarTarjeta.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_pagarTarjeta.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_pagarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pagarTarjetaActionPerformed(evt);
            }
        });

        boton_deposito.setActionCommand("deposito");
        boton_deposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_deposito.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_deposito.setLabel("Deposito");
        boton_deposito.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_deposito.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_depositoActionPerformed(evt);
            }
        });

        boton_pagarServicio.setActionCommand("pagarServicio");
        boton_pagarServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_pagarServicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_pagarServicio.setLabel("Pagar Servicio");
        boton_pagarServicio.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_pagarServicio.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_pagarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_pagarServicioActionPerformed(evt);
            }
        });

        boton_consultarSaldo.setActionCommand("consultarSaldo");
        boton_consultarSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_consultarSaldo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_consultarSaldo.setLabel("Consultar Saldo");
        boton_consultarSaldo.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_consultarSaldo.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_consultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_consultarSaldoActionPerformed(evt);
            }
        });

        boton_acercaSistema.setActionCommand("acercaSistema");
        boton_acercaSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_acercaSistema.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_acercaSistema.setLabel("Acerca del Sistema");
        boton_acercaSistema.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_acercaSistema.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_acercaSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_acercaSistemaActionPerformed(evt);
            }
        });

        boton_transferenciaCuenta.setActionCommand("transferenciaCuentas");
        boton_transferenciaCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_transferenciaCuenta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_transferenciaCuenta.setLabel("Transferencia entre Cuentas");
        boton_transferenciaCuenta.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_transferenciaCuenta.setPreferredSize(new java.awt.Dimension(245, 35));
        boton_transferenciaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_transferenciaCuentaActionPerformed(evt);
            }
        });

        boton_salir1.setActionCommand("salir");
        boton_salir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_salir1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_salir1.setLabel("Salir");
        boton_salir1.setMinimumSize(new java.awt.Dimension(245, 35));
        boton_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salir1ActionPerformed(evt);
            }
        });

        botonesMenu.setLayer(boton_pagarTarjeta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_deposito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_pagarServicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_consultarSaldo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_acercaSistema, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_transferenciaCuenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        botonesMenu.setLayer(boton_salir1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout botonesMenuLayout = new javax.swing.GroupLayout(botonesMenu);
        botonesMenu.setLayout(botonesMenuLayout);
        botonesMenuLayout.setHorizontalGroup(
            botonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(botonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(boton_pagarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_deposito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_pagarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_acercaSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(boton_consultarSaldo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_transferenciaCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_salir1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        botonesMenuLayout.setVerticalGroup(
            botonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_transferenciaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(boton_consultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(boton_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(boton_pagarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(boton_pagarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(boton_acercaSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(boton_salir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        separador.setMinimumSize(new java.awt.Dimension(5, 425));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(181, 181, 181));
        label1.setMinimumSize(new java.awt.Dimension(5, 425));
        label1.setPreferredSize(new java.awt.Dimension(5, 425));

        separador.setLayer(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout separadorLayout = new javax.swing.GroupLayout(separador);
        separador.setLayout(separadorLayout);
        separadorLayout.setHorizontalGroup(
            separadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        separadorLayout.setVerticalGroup(
            separadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(separadorLayout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPane3.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane3.setForeground(new java.awt.Color(153, 153, 153));

        panel1.setBackground(new java.awt.Color(153, 153, 153));
        panel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        boton_cancelarTransaccion.setActionCommand("cancelarTransaccion");
        boton_cancelarTransaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_cancelarTransaccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_cancelarTransaccion.setForeground(new java.awt.Color(51, 51, 51));
        boton_cancelarTransaccion.setLabel("Cancelar Transaccion");
        boton_cancelarTransaccion.setMaximumSize(new java.awt.Dimension(190, 30));
        boton_cancelarTransaccion.setMinimumSize(new java.awt.Dimension(190, 30));
        boton_cancelarTransaccion.setPreferredSize(new java.awt.Dimension(190, 30));
        boton_cancelarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarTransaccionActionPerformed(evt);
            }
        });

        boton_confirmarTransaccion.setActionCommand("confirmarTransaccion");
        boton_confirmarTransaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_confirmarTransaccion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_confirmarTransaccion.setForeground(new java.awt.Color(51, 51, 51));
        boton_confirmarTransaccion.setLabel("Confirmar Transaccion");
        boton_confirmarTransaccion.setMinimumSize(new java.awt.Dimension(190, 30));
        boton_confirmarTransaccion.setPreferredSize(new java.awt.Dimension(190, 30));
        boton_confirmarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_confirmarTransaccionActionPerformed(evt);
            }
        });

        cuentaDestino.setBackground(new java.awt.Color(255, 255, 255));
        cuentaDestino.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestinoActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 1, 0));
        label2.setText("Cuenta de Destino");

        cuentaDestino1.setBackground(new java.awt.Color(255, 255, 255));
        cuentaDestino1.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestino1ActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 1, 0));
        label3.setText("Nombre de Destinatario");

        cuentaDestino2.setBackground(new java.awt.Color(255, 255, 255));
        cuentaDestino2.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestino2ActionPerformed(evt);
            }
        });

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 1, 0));
        label4.setText("Nombre de Destinatario");

        cuentaDestino3.setBackground(new java.awt.Color(255, 255, 255));
        cuentaDestino3.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestino3ActionPerformed(evt);
            }
        });

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 1, 0));
        label5.setText("Monto");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 1, 0));
        label6.setText("Cuenta de Origen");

        cuentaDestino4.setBackground(new java.awt.Color(196, 196, 196));
        cuentaDestino4.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino4.setEnabled(false);
        cuentaDestino4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestino4ActionPerformed(evt);
            }
        });

        cuentaDestino5.setBackground(new java.awt.Color(196, 196, 196));
        cuentaDestino5.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestino5.setEnabled(false);
        cuentaDestino5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaDestino5ActionPerformed(evt);
            }
        });

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 1, 0));
        label7.setText("Saldo");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuentaDestino2)
                    .addComponent(cuentaDestino)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuentaDestino1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuentaDestino3)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cuentaDestino5)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(boton_cancelarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(boton_confirmarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentaDestino4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cuentaDestino4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuentaDestino5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuentaDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cuentaDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuentaDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_confirmarTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_cancelarTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jLayeredPane3.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonesMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonesMenu))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu Principal", jPanel1);

        jLayeredPane1.setLayer(fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bienvenido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jTabbedPane1)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        InterfazPrincipal.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout InterfazPrincipalLayout = new javax.swing.GroupLayout(InterfazPrincipal);
        InterfazPrincipal.setLayout(InterfazPrincipalLayout);
        InterfazPrincipalLayout.setHorizontalGroup(
            InterfazPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        InterfazPrincipalLayout.setVerticalGroup(
            InterfazPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterfazPrincipalLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(InterfazPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/primer_final/Fondo1020x641.png"))); // NOI18N
        fondo1.setToolTipText("");
        fondo1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        fondo1.setMinimumSize(new java.awt.Dimension(1020, 640));
        fondo1.setOpaque(true);
        fondo1.setPreferredSize(new java.awt.Dimension(1020, 640));
        jDesktopPane1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Button botonPresionadoActualmente = null;

    private void boton_consultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_consultarSaldoActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_consultarSaldo.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_consultarSaldo;
    }//GEN-LAST:event_boton_consultarSaldoActionPerformed

    private void boton_transferenciaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_transferenciaCuentaActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        // Restaurar el color original del botón anteriormente presionado
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_transferenciaCuenta.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_transferenciaCuenta;
        
    }//GEN-LAST:event_boton_transferenciaCuentaActionPerformed

    private void cuentaDestino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestino2ActionPerformed
        
    }//GEN-LAST:event_cuentaDestino2ActionPerformed

    private void cuentaDestino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestino1ActionPerformed

    private void cuentaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestinoActionPerformed

    private void boton_confirmarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_confirmarTransaccionActionPerformed
        
    }//GEN-LAST:event_boton_confirmarTransaccionActionPerformed

    private void boton_cancelarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarTransaccionActionPerformed
        
    }//GEN-LAST:event_boton_cancelarTransaccionActionPerformed

    private void boton_pagarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pagarServicioActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_pagarServicio.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_pagarServicio;
    }//GEN-LAST:event_boton_pagarServicioActionPerformed

    private void boton_pagarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_pagarTarjetaActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_pagarTarjeta.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_pagarTarjeta;
    }//GEN-LAST:event_boton_pagarTarjetaActionPerformed

    private void boton_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_depositoActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_deposito.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_deposito;
    }//GEN-LAST:event_boton_depositoActionPerformed

    private void boton_acercaSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_acercaSistemaActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_acercaSistema.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_acercaSistema;
    }//GEN-LAST:event_boton_acercaSistemaActionPerformed

    private void boton_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salir1ActionPerformed
        // Cambiar la apariencia del botón cuando se presiona
        if (botonPresionadoActualmente != null) {
            botonPresionadoActualmente.setBackground(new java.awt.Color(240, 240, 240));  // Color original del fondo
        }

        // Establecer el color oscuro para el botón actual
        boton_acercaSistema.setBackground(new java.awt.Color(102, 102, 102));

        // Actualizar la referencia al botón actualmente presionado
        botonPresionadoActualmente = boton_acercaSistema;
        
        System.exit(0);
    }//GEN-LAST:event_boton_salir1ActionPerformed

    private void cuentaDestino3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestino3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestino3ActionPerformed

    private void cuentaDestino4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestino4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestino4ActionPerformed

    private void cuentaDestino5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaDestino5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaDestino5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane InterfazPrincipal;
    private javax.swing.JLabel bienvenido;
    private java.awt.Button boton_acercaSistema;
    private java.awt.Button boton_cancelarTransaccion;
    private java.awt.Button boton_confirmarTransaccion;
    private java.awt.Button boton_consultarSaldo;
    private java.awt.Button boton_deposito;
    private java.awt.Button boton_pagarServicio;
    private java.awt.Button boton_pagarTarjeta;
    private java.awt.Button boton_salir1;
    private java.awt.Button boton_transferenciaCuenta;
    private javax.swing.JLayeredPane botonesMenu;
    private javax.swing.JTextField cuentaDestino;
    private javax.swing.JTextField cuentaDestino1;
    private javax.swing.JTextField cuentaDestino2;
    private javax.swing.JTextField cuentaDestino3;
    private javax.swing.JTextField cuentaDestino4;
    private javax.swing.JTextField cuentaDestino5;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fondo1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private javax.swing.JLabel logo;
    private java.awt.Panel panel1;
    private javax.swing.JLayeredPane separador;
    // End of variables declaration//GEN-END:variables
}
